import {Metadata} from "next";
import {GreetingsBlock} from "@/components/pages/main/greetingsBlock";
import {ServicesBlock} from "@/components/pages/main/servicesBlock";

export const metadata: Metadata = {
    title: 'Кредитный Гений',
    description: 'Generated by create next app',
    openGraph: {
        title: 'Кредитный Гений',
        description: 'Some description',
    }
}


const Home = () => {
    return (
        <main className="main">
            <GreetingsBlock/>
            <ServicesBlock />
        </main>
    )
}

export default Home
