import {Metadata} from "next";
import {GreetingsBlock} from "@/app/pages/main/greetingsBlock";
import {ServicesBlock} from "@/app/pages/main/servicesBlock";
import {HelpSection} from "@/app/pages/main/helpSection";
import {WhyWeSection} from "@/app/pages/main/whyWeSection";
import {LastSection} from "@/app/pages/main/lastSection";

export const metadata: Metadata = {
    title: 'Кредитный Гений',
    description: 'Generated by create next app',
    openGraph: {
        title: 'Кредитный Гений',
        description: 'Some description',
    }
}


const Home = () => {
    return (
        <main className="main">
            <GreetingsBlock/>
            <ServicesBlock/>
            <HelpSection/>
            <WhyWeSection/>
            <LastSection/>
        </main>
    )
}

export default Home
